**Numpy 입문**

In [1]:
import numpy as np

# numpy의 부동소수점 자리수 표시
np.set_printoptions(suppress=True, precision=4)

In [4]:
n1 = np.array([1, 2, 3, 4, 5, 6, 7]) # array 처리하면 , 사라짐

print(n1)

[1 2 3 4 5 6 7]


In [5]:
# 요소 수 확인
print(n1.shape) # 1차원 -> 그럼 2, 3차원은 어떻게?
# 1차원만 원소 수 체크 (?)
# , 뒤에 아무것도 없으면 1차원이다.

(7,)


In [ ]:
# 여기 코드 하나 못 적었따

In [7]:
# array 함수 통한 행렬(2개 배열) 변수 정의
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
n2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print(n2)
print(n2.shape) # 4행 3열/4개의 배열, 각 배열 3개의 원소가 있어요

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [23]:
n2[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
n2[:, 0]

array([ 1,  4,  7, 10])

In [25]:
n2[0, :]

array([1, 2, 3])

In [9]:
print(len(n2)) # 배열의 수(4개) =/= 원소의 수 (컴퓨터는 행렬로 이해하는 거 아님)

4


**zeros, ones 함수 이용**

In [11]:
n3 = np.zeros(5)
print(n3.shape)

# 원소 5개와 1차원임을 확인

(5,)


In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((2,3))
# (2,3) 행렬 : 2개의 배열이 있고 각 배열은 3개의 원소가 있음
# 보자마자 아 2차원이네~

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
n4 = np.ones((2,3))
print(n4.shape)

(2, 3)


In [16]:
# 모든 요속 정규분포를 따르는 변수와 3개 행렬

np.random.randn(2,3,4) # 평균 0, 표준편차 1 (표준화 =/= 정규화)

# 표준화 (x-x_bar)/sigma # n = len(x) 표준화 공식 꼭 기억하기.

# 2: 바깥쪽 배열 개수
# 3: 행(row) 개수
# 4: 열(column) 개수
# 즉, (2, 3, 4) 형태의 3차원 배열을 만들되,
# 그 안의 모든 값이 **평균 0, 표준편차 1의 정규분포 N(0,1)**을 따르는 랜덤 숫자라는 뜻이야.

array([[[-0.1568, -1.6463,  2.2563,  1.547 ],
        [-1.5042,  0.5682, -0.0177,  0.6678],
        [ 0.3508, -0.6282, -0.9201, -1.4277]],

       [[-0.3823, -0.6641, -1.2695, -0.2996],
        [-1.083 , -0.1046, -1.4479, -0.6294],
        [ 0.3661, -2.3914,  0.1241, -0.4894]]])

In [17]:
n5 = np.random.randn(2,3,4)
print(n5.shape)

(2, 3, 4)


**그래프 출력용 수치 배열 생성**

In [18]:
np.linspace(-1, 1, 11)

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [19]:
n6 = np.linspace(-1, 1, 11)
print(n6.shape)

(11,)


In [20]:
np.arange(-1, 1.2, 0.2)

array([-1. , -0.8, -0.6, -0.4, -0.2, -0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

**조작**

In [28]:
n2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
n2[:, 0]

In [31]:
n7 = np.array([False, True, False, True])
n2[n7] # 이런 걸 이용해서 이미지에서 masking 하는 기법

array([[ 4,  5,  6],
       [10, 11, 12]])

In [33]:
n8 = n2[n7]
n8.shape

(2, 3)

** reshape 함수 (**) **

In [34]:
# 초기 변수 1개 배열
np.array(range(24))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [36]:
n9 = np.array(range(24))
n9.shape

(24,)

In [37]:
n9.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [45]:
n9.reshape(3, 20) # 2번째 인수에 -1 말고는 뭐가 들어갈 수 있지?
# 🔹 -1의 의미

# -1은 자동 계산(auto infer) 을 뜻해.
# 즉, 전체 원소 개수를 유지하면서 나머지 차원 값을 자동으로 맞춰줘.

# 예를 들어:

# a = np.arange(60)   # 원소 60개
# a.reshape(3, -1)


# 이 경우,
# 3 × ? = 60 → ? = 20 이니까
# 자동으로 (3, 20)으로 만들어줘.

ValueError: cannot reshape array of size 24 into shape (3,20)

In [40]:
n9.reshape(3,-1,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [42]:
# n9.reshape(9,-1)
# 요소가 24개인데 24/9는 나머지가 있어서 에러 발생함.

In [48]:
# -1을 지정, 자동 계산
n9.reshape(2, -1, 4)
# 2개의 바깥 배열
# -1로 자동 계산
# 속성값은 4로
# 행은 계산할 필요 없음!
# → “행을 4로 맞추고, 열은 알아서 계산해줘
# 행,열 자리에 -1 위치 가능 둘 다!

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
n9.reshape(12, -1, 1)

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]],

       [[16],
        [17]],

       [[18],
        [19]],

       [[20],
        [21]],

       [[22],
        [23]]])

In [55]:
n9.reshape(3,-1,2,4)

# (3개의 큰 묶음 × 20개의 중간 묶음 × 2행 × 4열)

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]]],


       [[[ 8,  9, 10, 11],
         [12, 13, 14, 15]]],


       [[[16, 17, 18, 19],
         [20, 21, 22, 23]]]])

In [56]:
n9.reshape(3,8) # 행렬 = 3*8=24요소

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [58]:
n9.reshape(12, -1, 1)

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]],

       [[16],
        [17]],

       [[18],
        [19]],

       [[20],
        [21]],

       [[22],
        [23]]])

In [60]:
n9.reshape(12, -1,) # 1차원의 차이

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [62]:
n9.reshape(3,-1,2,3)
# 3*2*3 =18 인데 여기에 자연수 어떤수를 곱해도 24가 안돼여
# 인수분해해서 나온 값만...

ValueError: cannot reshape array of size 24 into shape (3,newaxis,2,3)

In [63]:
n9.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

축 교체하기

In [64]:
print(n2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [65]:
# 전치행렬 (행과 열을 바꿔주는 것)
# T : transpose
n2.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [66]:
n9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [68]:
n9.reshape(2, -1, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [69]:
n10 = n9.reshape(2,-1,4)

In [70]:
n10.shape

(2, 3, 4)

In [75]:
n11 =np.transpose(n10)
print(n11.shape)

(4, 3, 2)


In [77]:
n12 = np.transpose(n10, (1,2,0))
print(n12.shape)

# 어쩐지 유튜브에 보면 로봇으로 큐브 맞추는 영상이 한두개가 아니더라고요.

(3, 4, 2)


**행렬 연결하기**

In [81]:
# 변수로 사용할 배열
# 2행 3열 행렬
n13 = np.array(range(1,7)).reshape(2,3)
n14 = np.array(range(7,13)).reshape(2,3)

In [82]:
np.array(range(7,13)).reshape(2,3)

array([[ 7,  8,  9],
       [10, 11, 12]])

In [84]:
# 3요소 벡터
n15 = np.array(range(14,17))

In [87]:
print(n13)

[[1 2 3]
 [4 5 6]]


In [88]:
print(n14)

[[ 7  8  9]
 [10 11 12]]


In [89]:
# 행렬과 행렬 연결(세로 연결)
np.vstack([n13,n14]) # 담는 그릇 = 리스트
# stack vertically (수직 방향으로 쌓아줘)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [91]:
np.concatenate([n13, n14])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [90]:
np.hstack([n13,n14])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [92]:
np.concatenate([n13, n14], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [94]:
np.concatenate([n13, n14], axis=1)
#np.concatenate([배열1, 배열2], axis=축)
#axis=0 → 행 방향으로 붙이기
#열 방향으로 붙이기 (옆으로 추가)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

연산

In [95]:
# 넘파이 변수끼리 연산

# 원본변수
print(n13)
print(n14)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [98]:
n15 = n13 + n14
print(n15)

[[ 8 10 12]
 [14 16 18]]


브로드캐스팅

In [100]:
print(n1) # 벡터

[1 2 3 4 5 6 7]


In [101]:
# 모든 요소에서 같은 값을 빼고 싶어요
n1 - 4

array([-3, -2, -1,  0,  1,  2,  3])

유니버설 함수

In [102]:
np.linspace(0, 2*np.pi, 25)

array([0.    , 0.2618, 0.5236, 0.7854, 1.0472, 1.309 , 1.5708, 1.8326,
       2.0944, 2.3562, 2.618 , 2.8798, 3.1416, 3.4034, 3.6652, 3.927 ,
       4.1888, 4.4506, 4.7124, 4.9742, 5.236 , 5.4978, 5.7596, 6.0214,
       6.2832])

In [103]:
x = np.linspace(0, 2*np.pi, 25)

In [104]:
# y = sin(x) 계산
y = np.sin(x)
print(y)

[ 0.      0.2588  0.5     0.7071  0.866   0.9659  1.      0.9659  0.866
  0.7071  0.5     0.2588  0.     -0.2588 -0.5    -0.7071 -0.866  -0.9659
 -1.     -0.9659 -0.866  -0.7071 -0.5    -0.2588 -0.    ]


집계함수

In [105]:
n1

array([1, 2, 3, 4, 5, 6, 7])

In [106]:
np.sum(n1)

np.int64(28)

In [107]:
np.mean(n1)

np.float64(4.0)

In [112]:
np.max(n1) # 최대값
# 최대 최소값 찾아내는 이유 = 데이터 범위를 알아내기 위해서

np.int64(7)

In [111]:
np.min(n1) # 최솟값

np.int64(1)

응용 예시

In [113]:
# 두 변수를 비교해서 일치하는 개수로 정확도 계산
# 2개의 넘파이 배열 준비

# 정답
yt = np.array([1,1,0,1,1,0,1,1,0,0])

# 예측
yp = np.array([1,1,0,1,1,1,0,0,1,1])

In [115]:
# 정답(y)과 예측(y_pred) 잘 맞나? (동시비교)

matched = (yt == yp)
print(matched)

[ True  True  True  True  True False False False False False]


In [116]:
matched.sum() # True = 1이니까

np.int64(5)

In [119]:
# 맞은 개수
correct = matched.sum()
# 전체 개수
total = len(matched)

In [117]:
matched.mean()

np.float64(0.5)

In [124]:
# 정확도 계산
accuarcy = correct / total
print(accuarcy)
print(f'''
      정답 수: {correct},
      전체 수: {total},
      정확도 : {accuarcy: .3f} # 포맷 함수 적용
      ''')

0.5

      정답 수: 5,
      전체 수: 10,
      정확도 :  0.500 # 포맷 함수 적용
      


벡터값을 1차 함수로 변환 [0,1] 범위로 제한 >> 정규화Nomalize

In [125]:
# 모든 값을 [0,1] 범위에 포함하도록 변환하고 싶어요

print(n1)

[1 2 3 4 5 6 7]


In [128]:
n1_max = n1.max()
n1_min = n1.min()
print(n1_max, n1_min)

7 1


In [129]:
# 브로드캐스팅 써서 변환하기 min-max scaling

(n1-n1_min) / (n1_max - n1_min)

# n1_max - n1_min = 데이터 범위 = total
# ni_min = 0, n1_max = 1로 생각하면 좀 더 쉽다...



array([0.    , 0.1667, 0.3333, 0.5   , 0.6667, 0.8333, 1.    ])

참고
- 왜 평균을 사용하는 알고리즘들이 다 이상치에 민감할까요?

In [130]:
팀원_키 = [173, 174, 182, 177, 176]

np.mean(팀원_키)

np.float64(176.4)

In [136]:
팀원_키.append(207)
np.mean(팀원_키)

np.float64(190.0)

In [137]:
# 이상치를 처리 >> 이상치 제거, 이상치 대체(평균값으로)
# 데이터 분포를 보고 1) 평균, 2) 중위수(median), 회귀분석 돌려서 평균값과 비교해서 처리-> 다음에 할거임!
팀원_키_수정 = [173, 174, 182, 177, 176, 176.4] # 평균값으로 대체
np.mean(팀원_키_수정)

np.float64(176.4)

특정 조건을 만족하는 행 추출

In [138]:
print(n2)
# n2의 0번째 열이 짝수인지 판단하고 싶어요
print(n2[:,0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  4  7 10]


In [142]:
print(n2[:,0])

[ 1  4  7 10]


In [139]:
n2[:, 0] % 2 == 0

array([False,  True, False,  True])

In [140]:
n2[n2[:,0] % 2 == 0]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [141]:
# 두번째 방법
condition = n2[:, 0] % 2 == 0
n2[condition]

array([[ 4,  5,  6],
       [10, 11, 12]])