In [1]:
!pip list

Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
absolufy-imports                         0.3.1
accelerate                               1.11.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.1
aiosignal                                1.4.0
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.17.0
altair                                   5.5.0
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.11.0
anywidget                                0.9.18
argon2-cffi                              25.1.0
argon2-cffi-bindings               

In [2]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr1) # 1차원
print(arr2) # 2차원

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
# 난수 이용한 2차원 배열
# randn : random normal distribution(정규분포)
# 정규분포인가? normal, 정규, 가우시안이면 보통 정규분포임

np.random.randn(3)

array([ 0.58309989, -1.53596477, -0.07242771])

In [ ]:
arr3 = np.random.randn(3)
arr4 = np.random.randn(2,3)

print(arr4)

[[ 0.13021322 -0.13100472 -0.84346945]
 [-1.04639348  1.77674506  0.0560966 ]]


In [ ]:
# 원소를 0 또는 1로 초기화

arr5 = np.zeros(5)
arr6 = np.ones((2,3)) # ones는 튜플로 표현해야 함

print(arr5)
print(arr6)


[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# arange()와 reshape()
# arange() : array + range
# arange(start, end, step)
# 토치에서는 view

arr7 = np.arange(20,200,10)
print(arr7)
print(arr7.shape)
print(len(arr7))

[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
(18,)
18


In [ ]:
# 반드시 알아야 해요(변환!! 차원 왔다갔다 하는 거)
arr7.reshape(3,-1)

array([[ 20,  30,  40,  50,  60,  70],
       [ 80,  90, 100, 110, 120, 130],
       [140, 150, 160, 170, 180, 190]])

In [ ]:
arr8 = arr7.reshape(3,-1)

In [ ]:
# 배열 다루기
np.arange(1,21,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
ar1 = np.arange(1,21,1)
print(ar1[1]) # 인덱싱

2


In [ ]:
len(ar1)

20

In [ ]:
ar1.reshape(5,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
ar2 = ar1.reshape(2,-1)
ar2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
ar2[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
ar2[1][1]

np.int64(12)

In [ ]:
ar2[1][1] = 100
print(ar2[1][1])
print(ar2)

100
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11 100  13  14  15  16  17  18  19  20]]


In [ ]:
print(ar2[0])
print(ar2[1])
print(ar2[0][-1])

# 추천작 오름차순/내림차순 정렬하면서 사용자한테 추천하는 프로그램 구현에 쓰임

[ 1  2  3  4  5  6  7  8  9 10]
[ 11 100  13  14  15  16  17  18  19  20]
10


In [8]:
# 배열의 산술연산 : 배열의 연산은 배열 원소에 각각 적용됨

ar1 = np.arange(1, 11, 1)
print(ar1)
ar2 = ar1 + 3 # broadcasting (각 원소에 적용됨)
print(ar2)
ar3 = ar2 * 3
print(ar3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13]
[12 15 18 21 24 27 30 33 36 39]


In [11]:
# 배열의 통계 메소드

arr = np.array([[5,7,9],[-7,-6,19],[6,9,11]])

print(arr)
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7


In [12]:
print(arr.max(axis=0)) # 행끼리 출력, pytorch에서는 axis 대신 dim

[ 6  9 19]


In [13]:
condition = arr > 0

In [14]:
condition.sum() # 이거보다 커야하지 않나?

np.int64(7)

In [17]:
# np.where

# arr < 0 # 조건식
# 조건식이 True이면 (arr < 0) >>> 0 반환, 아니면 arr 출력)
np.where(arr < 0, 0, arr)

array([[ 5,  7,  9],
       [ 0,  0, 19],
       [ 6,  9, 11]])

In [29]:
arr = [3, 1, 2]

arr.sort()         # ✅ 원본이 정렬됨
print(arr)         # [1, 2, 3]

arr = [3, 1, 2]
new_arr = sorted(arr)  # ✅ 새로운 리스트를 반환
print(arr)             # [3, 1, 2] (원본 유지)
print(new_arr)         # [1, 2, 3]


[1, 2, 3]
[3, 1, 2]
[1, 2, 3]


In [30]:
# np.sort(), arr.sort() 차이 : 원본 수정 여부
import numpy as np
arr = np.array([[3, 1, 2],
                [9, 8, 7]])

print(np.sort(arr, axis=1))
# 각 행(가로) 기준 정렬
# [[1, 2, 3],
#  [7, 8, 9]]

arr.sort(axis=0)  # 원본 배열이 열 단위로 정렬됨
print(arr)
# [[3, 1, 2],
#  [9, 8, 7]] → (axis=0이면 세로 기준 정렬)


[[1 2 3]
 [7 8 9]]
[[3 1 2]
 [9 8 7]]


In [31]:
# 텐서는 항상 새로운 배열 반환
import torch

t = torch.tensor([[3, 1, 2],
                  [9, 8, 7]])

values, indices = t.sort(dim=1)
print(values)
# tensor([[1, 2, 3],
#         [7, 8, 9]])

print(indices)
# tensor([[1, 2, 0],
#         [2, 1, 0]])  ← 원래 위치


tensor([[1, 2, 3],
        [7, 8, 9]])
tensor([[1, 2, 0],
        [2, 1, 0]])


In [32]:
arr10 = np.array([1,1,2,3,3,4,4,5,5])

In [33]:
# argsort() : 정렬된 인덱스

np.array([30,10,40,20])

array([30, 10, 40, 20])

In [34]:
arr11 = np.array([30,10,40,20])
print(arr11)

[30 10 40 20]


In [36]:
np.argsort(arr11) # 크기순 인덱스

array([1, 3, 0, 2])