In [1]:
import torch

random_tensor = torch.randn((2,3))

print(random_tensor)

tensor_like = torch.randn_like(random_tensor)

print(tensor_like) #동일크기 동일데이터타입 -1~+1 랜덤

tensor([[ 1.5684, -0.6605, -0.4829],
        [ 2.1905,  0.5303,  1.2047]])
tensor([[-0.8519, -0.1368, -0.1689],
        [ 0.1112,  1.7623,  1.4070]])


In [8]:
import torch

exam = torch.rand(3,1,4,1)
print(exam)
exam = exam.squeeze(dim=1)
print(exam)
exam = exam.unsqueeze(dim=0)
print(exam)

tensor([[[[0.0256],
          [0.7716],
          [0.2847],
          [0.9385]]],


        [[[0.1020],
          [0.1221],
          [0.5152],
          [0.1422]]],


        [[[0.9230],
          [0.5145],
          [0.6502],
          [0.8701]]]])
tensor([[[0.0256],
         [0.7716],
         [0.2847],
         [0.9385]],

        [[0.1020],
         [0.1221],
         [0.5152],
         [0.1422]],

        [[0.9230],
         [0.5145],
         [0.6502],
         [0.8701]]])
tensor([[[[0.0256],
          [0.7716],
          [0.2847],
          [0.9385]],

         [[0.1020],
          [0.1221],
          [0.5152],
          [0.1422]],

         [[0.9230],
          [0.5145],
          [0.6502],
          [0.8701]]]])


In [15]:
import torch

x = torch.tensor([[[1], [2], [3]]])
print(x)
print(x.shape) # torch.Size([1, 3, 1])
print(x.squeeze())
print(x.squeeze().shape) # torch.Size([3])

tensor([[[1],
         [2],
         [3]]])
torch.Size([1, 3, 1])
tensor([1, 2, 3])
torch.Size([3])


In [18]:
import torch

x = torch.tensor([[[1], [2], [3]]])
print(x)
print(x.shape) # torch.Size([1, 3, 1])
print(x.squeeze(dim=0))
print(x.squeeze(dim=0).shape) # torch.Size([3, 1])

tensor([[[1],
         [2],
         [3]]])
torch.Size([1, 3, 1])
tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])


In [12]:
x.squeeze()
print(x.shape)

torch.Size([1, 3, 1])


In [ ]:
import torch
